name: Build LaTeX document

on:
  push

jobs:
  build_paper:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow creating releases

    steps:
      - name: Checkout [${{ github.repository }}]
        uses: actions/checkout@v4

      - uses: haozhu10015/.github/actions/latex@main
        with:
          paper: article/article.tex slides/slides.tex